address: /survey-service
server:
  port: 8081

logging:
  file:
    max-size: 999MB
    path: .

  pattern:
    console: "%clr(%date{HH:mm:ss.SSS}) %level %clr(%logger{0}) : %message%n"
    file:    "%clr(%date) %level %clr(%logger :) %message%n"

  level:
    root: INFO
    org.springframework.web: INFO

spring:
  output:
    ansi:
      enabled: ALWAYS

  main:
    allow-bean-definition-overriding: true

  datasource:
    platform: postgres
    url: jdbc:postgresql://survey_service_db/survey_service?createDatabaseIfNotExist=true
    username: postgres
    password: postgres

  jpa:
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
        current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
      show-sql: true

    hibernate:
      ddl-auto: validate
    open-in-view: false
    show-sql: true

  liquibase:
    change-log: classpath:db-migrations/changelog.xml
    enabled: true